### ISSUE TITLE
Add the 'embed' tag like in PebbleTemplate / Twig

### ISSUE THREAD

**Issue by davy-claisse** [Keats/tera2#26]
The `embed` tag is not part of Jinja2 or Django but originally part of Twig, which is a derived form of both.

The goal of this tag is to get the ability to pass parameters to the embedded template by using the `with` keyword, for instance:

We declared the following template in the file **person.tera**.
```jinja2
Hello {{ name }}!
```

The `embed` tag allows us to use it like this (without getting information from Tera Context):
```jinja2
{% embed "person.tera" with { "name" : "World" } %}
{% endembed %}
```

I can give two good documentations of this tag:
- https://pebbletemplates.io/wiki/tag/embed/
- https://twig.symfony.com/doc/3.x/tags/embed.html

**Comment by Keats** [comment]
Isn't that the same as include with specifying the context in Jinja2? Either way, Tera prefers using macros than includes so that is not going to be added
