### ISSUE TITLE
Syntax like 'filter section' but for saving to a variable

### ISSUE THREAD

**Issue by asimpletune** [Keats/tera2#50]
Multi-line strings in tera can be a bit cumbersome at times. This is usually fine. There's a strong distinction between what is being rendered as a part of the template, and what is being saved as a variable. However, every now and then it would be very useful to be able to store part of a template rather than have it rendered. 

## how it could look

There is already existing inspiration for how this could look. Consider the following syntax:

```jinja
{# this kind of syntax is very nice because the arguments to the filter don't have to be quoted #}
{% filter upper %)
filter body goes inside
{% end filter %}

{# what if `set` worked similarly? #}
{% set foo %}
hello, {{ name }} <-- templating can happen inside

there're no quotes for strings, nor string concatenation
{% end set %}
```

With the above example, you could then later refer to the variable `foo`, but until then it won't otherwise be rendered. 

## why? 

This is useful mostly for ergonomic reasons, but they turn out to be quite practical as well. While it's theoretically true that you can make the same strings by concatenating,  in practice it doesn't always work out so well. 

This becomes most apparent when you need a string to match an exact format, including whitespace. Additionally, most projects have some kind of prettifier, and this tooling does not play well at all with dynamically creating html tags via string concatenation. 

Normally none of this is an issue because what you want is to just render the output directly anyway, so there's no strings involved to begin with. However, occasionally one needs to save it as a variable first and pass that around, before rendering. It's very difficult to do this cleanly in tera. 

## macros aren't enough

Macros don't support referencing variables defined outside the macro. In other words, anything inside a macro must be passed into it. 

I think this mostly makes sense and I wouldn't really want to change that, since it can help you reason about your code. Also, macros have to be defined and _then_ called, requiring two steps. Better would be to allow `set` to work like those "filter sections".

**Comment by Keats** [comment]
It's actually already implemented: https://github.com/Keats/tera2/blob/master/tera/src/snapshot_tests/rendering_inputs/success/set_blocks.txt
