### ISSUE TITLE
The order of keys is not preserved when mapping is created

### ISSUE THREAD

**Issue by azemlya** [Keats/tera2#59]
The order of keys is not preserved when mapping is created?

```
{% set m = {"name": "Alex", "age": 42, "vip": true, } -%}
{{ m }}
{{ {"name": "Alex", "age": 42, "vip": true, } }}
```

Output:

```
{"age": 42, "name": "Alex", "vip": true}
{"age": 42, "name": "Alex", "vip": true}
```

Why does the parser sort by keys?

**Comment by Keats** [comment]
It's not the parser it's the pretty printer of hashmap that sorts the keys before printing them so it's deterministic.

By default, order is not guaranteed anyway, you will need the enable the preserve_order feature to keep it. It will be correct when iterating but not when printing it. I guess I could not sort it when using that feature though.

**Comment by azemlya** [comment]
```
{% set m = {"name": "Alex", "age": 42, "vip": true, } -%}
{{ m }}
{% for k, v in m -%}
{{ k }} = {{ v }}
{% endfor -%}
```

Output:

```
{"age": 42, "name": "Alex", "vip": true}
age = 42
name = Alex
vip = true
```

Cargo.toml
```
[dependencies]
tera = { git = "https://github.com/Keats/tera2.git", branch = "master", features = ["fast", "preserve_order", "unicode", "glob_fs", ] }
```

**Comment by Keats** [comment]
ah yes of course I don't use the right map when creating the map in the parser 😮‍💨  https://github.com/Keats/tera2/pull/60
